# Generated by Django 4.1 on 2023-04-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
