# Generated by Django 4.1 on 2023-04-16 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('myblog', '0010_userprofileinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_picture',
        ),
    ]
